# Lesson 1 — NumPy Fundamentals

**Goal:** Understand why NumPy exists and how it is used for scientific computing.

Today we learn:

- Arrays
- Indexing
- Vectorization
- Broadcasting
- Matrix operations
- Why NumPy is faster than Python lists

---

# 1. Why Should You Care?

**NumPy** is one of the most important libraries in Python for **AI, Machine Learning, and Remote Sensing** because almost all scientific data is numerical.

Satellite images, NDVI values, temperature maps, and machine learning datasets are basically **large collections of numbers**.

Instead of processing thousands or millions of numbers one by one, NumPy allows Python to perform mathematical operations efficiently on entire datasets.

---

# 2. Core Concept (Short)

## What is NumPy?

**NumPy (Numerical Python)** is a Python library designed for fast numerical calculations.

The main object in NumPy is an **array**.

An array is a collection of numbers stored in a structured way.

### Python List

```python
numbers = [1, 2, 3, 4]
```

### NumPy Array

```python
import numpy as np

numbers = np.array([1, 2, 3, 4])
```

They look similar, but internally they work very differently.

---

## Array Dimensions

### 1D Array

Like a list:

```python
ndvi = np.array([0.3, 0.5, 0.8])
```

Structure:

```text
[0.3  0.5  0.8]
```

---

### 2D Array

Like a table:

```python
image = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
```

Structure:

```text
10 20 30
40 50 60
```

A satellite image is basically a **2D array of pixel values**.

---

# 3. Simple Example

Imagine temperature measurements:

```python
temperature = [20, 25, 30, 35]
```

You want to increase every value by **2**.

### With a Normal Python List

```python
temperature = [20, 25, 30, 35]

new_temperature = []

for t in temperature:
    new_temperature.append(t + 2)

print(new_temperature)
```

Output:

```text
[22, 27, 32, 37]
```

You need a loop.

---

### With NumPy

```python
import numpy as np

temperature = np.array([20, 25, 30, 35])

print(temperature + 2)
```

Output:

```text
[22 27 32 37]
```

NumPy applies the operation to all values automatically.

This is called **Vectorization**.

---

# 4. Remote Sensing / Environmental Example

A satellite image is not one number.

It is **millions of pixels**.

Example:

```python
ndvi = np.array([
    [0.2, 0.5, 0.8],
    [0.1, 0.6, 0.9],
    [0.3, 0.4, 0.7]
])
```

Each number represents vegetation strength.

Imagine you want to find healthy vegetation:

**NDVI > 0.5**

With NumPy:

```python
healthy = ndvi > 0.5

print(healthy)
```

Output:

```text
False False True
False True  True
False False True
```

Every pixel is checked at once.

This idea is the foundation of:

- NDVI maps
- Land cover classification
- Image processing
- Machine learning features

---

# 5. Important NumPy Concepts

## A) Indexing

Indexing means accessing specific values.

Example:

```python
ndvi = np.array([0.2, 0.5, 0.8])

print(ndvi[1])
```

Output:

```text
0.5
```

Remember:

Python starts counting from **0**.

---

For 2D arrays:

```python
image = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(image[0, 2])
```

Meaning:

- Row **0**
- Column **2**

Output:

```text
30
```

---

## B) Vectorization

Vectorization means performing operations on an **entire array** instead of using loops.

Example:

```python
ndvi = np.array([0.2, 0.5, 0.8])

ndvi + 0.1
```

Python automatically does:

```text
0.2 + 0.1
0.5 + 0.1
0.8 + 0.1
```

Result:

```text
[0.3 0.6 0.9]
```

---

## C) Broadcasting

Broadcasting allows NumPy to perform operations between arrays of different sizes.

Example:

```python
temperatures = np.array([20, 25, 30])

temperatures + 5
```

NumPy understands:

```text
[20,25,30]
+
[5,5,5]

=
[25,30,35]
```

It automatically expands the smaller value.

---

## D) Matrix Operations

A matrix is a rectangular arrangement of numbers.

Example:

```text
1 2
3 4
```

In AI:

- Images are matrices.
- Neural networks use matrix operations.
- Machine learning calculations depend heavily on matrices.

NumPy allows:

```python
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

A + B
```

Output:

```text
[[ 6  8]
 [10 12]]
```

---

# 6. Why Is NumPy Faster Than Python Lists?

This is very important.

Python lists:

```python
[1, 2, 3, 4]
```

are flexible.

Each number is stored as a separate Python object.

NumPy arrays:

```python
[1 2 3 4]
```

store numbers in a compact block of memory.

### Advantages

### 1. Less Memory

Numbers are stored efficiently.

### 2. Faster Calculations

NumPy uses optimized low-level code (written in **C**).

### 3. Vectorization

Operations happen on whole arrays instead of slow Python loops.

Think of it like this:

### Python List

```text
Number 1 → process
Number 2 → process
Number 3 → process
Number 4 → process
```

### NumPy

```text
[1 2 3 4]
       ↓
Fast mathematical operation
```

---

# 7. Mini Coding Example

```python
import numpy as np

ndvi = np.array([0.2, 0.6, 0.8])

average = np.mean(ndvi)

print(average)
```

---

# Line by Line Explanation

## Import NumPy

```python
import numpy as np
```

Loads NumPy.

`np` is a short nickname.

---

## Create an Array

```python
ndvi = np.array([0.2, 0.6, 0.8])
```

Creates a NumPy array.

---

## Calculate the Average

```python
average = np.mean(ndvi)
```

Calculates the average NDVI.

Calculation:

```text
(0.2 + 0.6 + 0.8) / 3
```

---

## Print the Result

```python
print(average)
```

Displays the result.

---

# 8. Practice Together

## Question 1

Look at this code:

```python
import numpy as np

values = np.array([10, 20, 30])

print(values[1])
```

Answer:

1. What is the output?
2. Why does it print that value?
3. What is the index of the first value?

*(Answer first; I will guide you before moving to the next question.)*

---

# 9. Mini Quiz (Don't Answer Yet)

## Conceptual Questions

1. What is the difference between a Python list and a NumPy array?

2. What does vectorization mean?

3. Why is NumPy useful for satellite imagery?

---

## Multiple Choice

What will this produce?

```python
import numpy as np

x = np.array([1, 2, 3])

print(x * 2)
```

A)

```text
[1,2,3,1,2,3]
```

B)

```text
[2,4,6]
```

C)

```text
[1,4,9]
```

D)

```text
Error
```

---

## Practical Scenario

You have NDVI values:

```python
ndvi = np.array([0.2, 0.7, 0.8, 0.4])
```

Write NumPy code that finds which values are greater than **0.5**.

---

# 10. Ready to Move On?

Before moving to the next NumPy lesson, you should be able to explain:

✅ What a NumPy array is.  
✅ Why arrays are better than lists for numerical data.  
✅ How indexing works.  
✅ What vectorization means.  
✅ What broadcasting does.  
✅ Why NumPy is essential for AI and Remote Sensing.

---

# 🌍 Connection to Your Future Work

This is where your Remote Sensing background starts connecting strongly with Python.

```
Sentinel-2 Band
        ↓
Millions of Pixel Values
        ↓
NumPy Array
        ↓
Mathematical Operations
        ↓
NDVI / Classification / Machine Learning Model
```

NumPy is the mathematical engine behind many environmental data workflows.

Learning it well will make **Pandas**, **Machine Learning**, and **image processing** much easier.